id: P001721
initial_creation_type: ocr
source_metadata:
  id: bdr:W29329
  title: བོད་རྒྱ་ཚིག་མཛོད་ཆེན་མོ།
  author: ''
  volumes:
    dbecf21f3a0b4b0d9a54f9e026ddc82a:
      image_group_id: I1KG15042
      title: ''
      volume_number: 1
      total_pages: 1058
    538e883cc2234ebda5c3c655e6dce953:
      image_group_id: I1KG15043
      title: ''
      volume_number: 2
      total_pages: 1328
    3ed2034c1df642a8a22e18a1174f9f55:
      image_group_id: I1KG15044
      title: ''
      volume_number: 3
      total_pages: 1002
