id: I379B6683
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T13:02:05+00:00'
last_modified: '2022-06-07T14:12:15.954509+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29329
  title: བོད་རྒྱ་ཚིག་མཛོད་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9C63:
      image_group_id: I1KG15042
      title: ''
      total_pages: 1058
      order: 1
      base_file: 9C63.txt
    088D:
      image_group_id: I1KG15043
      title: ''
      total_pages: 1328
      order: 2
      base_file: 088D.txt
    '4971':
      image_group_id: I1KG15044
      title: ''
      total_pages: 1002
      order: 3
      base_file: 4971.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
